name: Publish Docker Compose Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker Compose image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker-compose.yml
          push: true
          tags: ghcr.io/julianruano/evaluation_system_backend:latest
          
