name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        run: |
          docker-compose build web
          docker tag evaluation-system:latest ghcr.io/julianruano/evaluation_system_backend/evaluation-system:latest
          docker push ghcr.io/julianruano/evaluation_system_backend/evaluation-system:latest

      - name: Clean up Docker cache (optional)
        run: docker image prune -f